### PR TITLE
fix: "ge" method did not add up weights of parallel edges

### PR DESCRIPTION
**Pull request by szhorvat**
This is the same fix that I made for igraph's embedded PRPACK here: https://github.com/igraph/igraph/issues/972

In short, the result was wrong when:

 - the graph was weighted
 - it was a multigraph
 - the Gaussian elimination method was used (default for a vertex count < 128)

### CODE REVIEW

**Comment by szhorvat** [comment]
@dgleich Should we have opened this PR as well as #5 in your repo here? https://github.com/dgleich/prpack

**Comment by dgleich** [comment]
yes, that's a good idea.

**Comment by szhorvat** [comment]
In that case, I'll change all references within the igraph sources/docs to your fork of the repo instead of here (since this one doesn't seem to be maintained anymore)

**Comment by szhorvat** [comment]
Submitted to https://github.com/dgleich/prpack/pull/2 instead.

**Pull request closed without merging**
